apiVersion: v1
kind: Service
metadata:
  name: laravel-svc
  namespace: {{ .Values.namespace }} #Modificable values
spec:
  selector:
    app: laravel
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
  namespace: {{ .Values.namespace }} #Modificable values
spec:
  capacity:
    storage: {{ .Values.laravel.pvstorage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.laravel.path}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc
  namespace: {{ .Values.namespace }} #Modificable values
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.laravel.pvcstorage }} #Modificable values

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: {{ .Values.namespace }} #Modificable values
  labels:
    app: laravel
spec:
  replicas: {{ .Values.laravel.replicas}}
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      volumes:
      - name: laravel-persistent-storage
        persistentVolumeClaim:
          claimName: laravel-pvc
      containers:
      - name: laravel
        image: bitnami/laravel:{{ .Values.laravel.image.version }} #Versión modificable values
        ports:
          - containerPort: 8000
        env:
          - name: LARAVEL_PORT_NUMBER
            value: "8000"
          - name: LARAVEL_SKIP_COMPOSER_UPDATE
            value: "no"
          - name: LARAVEL_SKIP_DATABASE
            value: "no"
          - name: LARAVEL_DATABASE_TYPE
            value: "mysql"
          - name: LARAVEL_DATABASE_HOST
            value: "db-svc"
          - name: LARAVEL_DATABASE_PORT_NUMBER
            value: "3306"
          - name: LARAVEL_DATABASE_NAME
            value: "{{ .Values.mysql.db.dbname }}"
          - name: LARAVEL_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user
          - name: LARAVEL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
        resources:
          requests:
            cpu: {{ .Values.laravel.requests.cpu }} #Modificable values
            memory: {{ .Values.laravel.requests.memory }} #Modificable values
          limits:
            cpu: {{ .Values.laravel.limits.cpu }} #Modificable values
            memory: {{ .Values.laravel.limits.memory }} #Modificable values
        livenessProbe:
          httpGet: 
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: laravel-persistent-storage
          mountPath: /mnt/data

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: {{ .Values.namespace }} #Modificable values
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.laravel.ingress.host }} #Modificable values
    http:
      paths:
      - path: {{ .Values.laravel.ingress.path }} #Modificable values
        pathType: Prefix
        backend:
          service:
            name: laravel-svc
            port:
              number: 8000