apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  user: {{ .Values.mysql.db.user }}
  password: {{ .Values.mysql.db.password }} 
  root_password: {{ .Values.mysql.db.root_password }}
  dbname: {{ .Values.mysql.db.dbname }}

# | b64enc sirve para codificar el string en base64